/*
Copyright 2020 The Manba Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	time "time"

	configurationv1beta1 "github.com/domgoer/manba-ingress/pkg/apis/configuration/v1beta1"
	versioned "github.com/domgoer/manba-ingress/pkg/client/clientset/versioned"
	internalinterfaces "github.com/domgoer/manba-ingress/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/domgoer/manba-ingress/pkg/client/listers/configuration/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ManbaIngressInformer provides access to a shared informer and lister for
// ManbaIngresses.
type ManbaIngressInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.ManbaIngressLister
}

type manbaIngressInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewManbaIngressInformer constructs a new informer for ManbaIngress type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewManbaIngressInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredManbaIngressInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredManbaIngressInformer constructs a new informer for ManbaIngress type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredManbaIngressInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ConfigurationV1beta1().ManbaIngresses(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ConfigurationV1beta1().ManbaIngresses(namespace).Watch(options)
			},
		},
		&configurationv1beta1.ManbaIngress{},
		resyncPeriod,
		indexers,
	)
}

func (f *manbaIngressInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredManbaIngressInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *manbaIngressInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&configurationv1beta1.ManbaIngress{}, f.defaultInformer)
}

func (f *manbaIngressInformer) Lister() v1beta1.ManbaIngressLister {
	return v1beta1.NewManbaIngressLister(f.Informer().GetIndexer())
}
