---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: manba-ingress
  name: manba-ingress
  namespace: manba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manba-ingress
  template:
    metadata:
      annotations:
        prometheus.io/port: "9542"
        prometheus.io/scrape: "true"
      labels:
        app: manba-ingress
    spec:
      serviceAccountName: manba-serviceaccount
      containers:
        - name: ingress-controller
          args:
            - --manba-api-server-addr=api-server.default:9092
            - --admission-webhook-listen=0.0.0.0:8081
            - --publish-service=default/api-proxy
            - --update-status=false
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          image: domgoer/ingress-controller
          imagePullPolicy: IfNotPresent
          ports:
            - name: webhook
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
