apiVersion: configuration.manba.io/v1beta1
kind: ManbaCluster
metadata:
  name: my-cluster
  namespace: default
spec:
  trafficPolicy:
    loadBalancer: RoundRobin
    maxQPS: 100
    circuitBreaker:
      closeTimeout: 500
      halfTrafficRate: 50
      rateCheckPeriod: 30
      failureRateToClose: 50
      succeedRateToOpen: 50
  subsets:
  - name: v1
    labels:
      app: api-server
    trafficPolicy:
      loadBalancer: IPHash
      maxQPS: 500
      circuitBreaker:
        closeTimeout: 500
        halfTrafficRate: 50
        rateCheckPeriod: 30
        failureRateToClose: 50
        succeedRateToOpen: 50
  - name: v2
    labels:
      app: api-proxy

---

apiVersion: configuration.manba.io/v1beta1
kind: ManbaIngress
metadata:
  name: my-api
  namespace: default
spec:
  http:
  - match:
    - host: blog.domgoer.io
      rules:
      - uri:
          pattern: /
          method: GET
    - host: github.domgoer.io
      rules:
        - uri:
            pattern: /blog
            method: POST
    rewrite:
      uri: /domgoer/blog
    accessControl:
      blacklist:
      - 1.1.1.1
      whitelist:
      - 2.2.2.2
    retries:
      interval: 500
      maxTimes: 3
      codes:
      - 500
      - 409
    route:
    - cluster:
        name: my-cluster
        port: 9093
        subset: v1
    - cluster:
        name: my-cluster
        port: 9092
        subset: v2
    split:
    - cluster:
        name: my-cluster
        subset: v1
        port: 9093
      rate: 30
    renderTemplate:
      objects:  
      - name: test
        attrs:
        - name: test
          extractExp: test
        flatAttrs: true
