package v1beta1

import (
	"encoding/json"
	"github.com/golang/glog"
)

// DeepCopyInto ...
func (in *ManbaHTTPRule) DeepCopyInto(out *ManbaHTTPRule) {
	deepcopy(in, out)
}

// DeepCopyInto ...
func (in *ManbaHTTPRoute) DeepCopyInto(out *ManbaHTTPRoute) {
	deepcopy(in, out)
}

// DeepCopyInto ...
func (in *ManbaHTTPRouting) DeepCopyInto(out *ManbaHTTPRouting) {
	deepcopy(in, out)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManbaHTTPRouteMatch) DeepCopyInto(out *ManbaHTTPRouteMatch) {
	deepcopy(in, out)
}

// DeepCopyInto ...
func (in *TrafficPolicy) DeepCopyInto(out *TrafficPolicy) {
	deepcopy(in, out)
}

// DeepCopyInto deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManbaIngress) DeepCopyInto(out *ManbaIngress) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	inSpec, outSpec := in.Spec, out.Spec
	deepcopy(&inSpec, &outSpec)
}

func deepcopy(in, out interface{}) {
	b, err := json.Marshal(in)
	if err != nil {
		glog.Errorf("unexpected error copying configuration: %v", err)
	}
	err = json.Unmarshal(b, out)
	if err != nil {
		glog.Errorf("unexpected error copying configuration: %v", err)
	}
}
