// +build !ignore_autogenerated

/*
Copyright 2020 The Manba Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1beta1

import (
	networkingv1beta1 "k8s.io/api/networking/v1beta1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManbaIngress.
func (in *ManbaIngress) DeepCopy() *ManbaIngress {
	if in == nil {
		return nil
	}
	out := new(ManbaIngress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManbaIngress) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManbaIngressBackend.
func (in *ManbaIngressBackend) DeepCopy() *ManbaIngressBackend {
	if in == nil {
		return nil
	}
	out := new(ManbaIngressBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManbaIngressList) DeepCopyInto(out *ManbaIngressList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManbaIngress, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManbaIngressList.
func (in *ManbaIngressList) DeepCopy() *ManbaIngressList {
	if in == nil {
		return nil
	}
	out := new(ManbaIngressList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManbaIngressList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManbaIngressPath.
func (in *ManbaIngressPath) DeepCopy() *ManbaIngressPath {
	if in == nil {
		return nil
	}
	out := new(ManbaIngressPath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManbaIngressRoute.
func (in *ManbaIngressRoute) DeepCopy() *ManbaIngressRoute {
	if in == nil {
		return nil
	}
	out := new(ManbaIngressRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManbaIngressRule.
func (in *ManbaIngressRule) DeepCopy() *ManbaIngressRule {
	if in == nil {
		return nil
	}
	out := new(ManbaIngressRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManbaIngressSpec) DeepCopyInto(out *ManbaIngressSpec) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]ManbaIngressRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = make([]networkingv1beta1.IngressTLS, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManbaIngressSpec.
func (in *ManbaIngressSpec) DeepCopy() *ManbaIngressSpec {
	if in == nil {
		return nil
	}
	out := new(ManbaIngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManbaIngressStatus) DeepCopyInto(out *ManbaIngressStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManbaIngressStatus.
func (in *ManbaIngressStatus) DeepCopy() *ManbaIngressStatus {
	if in == nil {
		return nil
	}
	out := new(ManbaIngressStatus)
	in.DeepCopyInto(out)
	return out
}
