/*
Copyright 2020 The Manba Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/domgoer/manba-ingress/pkg/apis/configuration/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeManbaClusters implements ManbaClusterInterface
type FakeManbaClusters struct {
	Fake *FakeConfigurationV1beta1
	ns   string
}

var manbaclustersResource = schema.GroupVersionResource{Group: "configuration.manba.io", Version: "v1beta1", Resource: "manbaclusters"}

var manbaclustersKind = schema.GroupVersionKind{Group: "configuration.manba.io", Version: "v1beta1", Kind: "ManbaCluster"}

// Get takes name of the manbaCluster, and returns the corresponding manbaCluster object, and an error if there is any.
func (c *FakeManbaClusters) Get(name string, options v1.GetOptions) (result *v1beta1.ManbaCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(manbaclustersResource, c.ns, name), &v1beta1.ManbaCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ManbaCluster), err
}

// List takes label and field selectors, and returns the list of ManbaClusters that match those selectors.
func (c *FakeManbaClusters) List(opts v1.ListOptions) (result *v1beta1.ManbaClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(manbaclustersResource, manbaclustersKind, c.ns, opts), &v1beta1.ManbaClusterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.ManbaClusterList{ListMeta: obj.(*v1beta1.ManbaClusterList).ListMeta}
	for _, item := range obj.(*v1beta1.ManbaClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested manbaClusters.
func (c *FakeManbaClusters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(manbaclustersResource, c.ns, opts))

}

// Create takes the representation of a manbaCluster and creates it.  Returns the server's representation of the manbaCluster, and an error, if there is any.
func (c *FakeManbaClusters) Create(manbaCluster *v1beta1.ManbaCluster) (result *v1beta1.ManbaCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(manbaclustersResource, c.ns, manbaCluster), &v1beta1.ManbaCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ManbaCluster), err
}

// Update takes the representation of a manbaCluster and updates it. Returns the server's representation of the manbaCluster, and an error, if there is any.
func (c *FakeManbaClusters) Update(manbaCluster *v1beta1.ManbaCluster) (result *v1beta1.ManbaCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(manbaclustersResource, c.ns, manbaCluster), &v1beta1.ManbaCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ManbaCluster), err
}

// Delete takes name of the manbaCluster and deletes it. Returns an error if one occurs.
func (c *FakeManbaClusters) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(manbaclustersResource, c.ns, name), &v1beta1.ManbaCluster{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeManbaClusters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(manbaclustersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.ManbaClusterList{})
	return err
}

// Patch applies the patch and returns the patched manbaCluster.
func (c *FakeManbaClusters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.ManbaCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(manbaclustersResource, c.ns, name, pt, data, subresources...), &v1beta1.ManbaCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ManbaCluster), err
}
