/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/domgoer/manba-ingress/pkg/apis/configuration/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeManbaIngresses implements ManbaIngressInterface
type FakeManbaIngresses struct {
	Fake *FakeConfigurationV1beta1
	ns   string
}

var manbaingressesResource = schema.GroupVersionResource{Group: "configuration.manba.io", Version: "v1beta1", Resource: "manbaingresses"}

var manbaingressesKind = schema.GroupVersionKind{Group: "configuration.manba.io", Version: "v1beta1", Kind: "ManbaIngress"}

// Get takes name of the manbaIngress, and returns the corresponding manbaIngress object, and an error if there is any.
func (c *FakeManbaIngresses) Get(name string, options v1.GetOptions) (result *v1beta1.ManbaIngress, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(manbaingressesResource, c.ns, name), &v1beta1.ManbaIngress{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ManbaIngress), err
}

// List takes label and field selectors, and returns the list of ManbaIngresses that match those selectors.
func (c *FakeManbaIngresses) List(opts v1.ListOptions) (result *v1beta1.ManbaIngressList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(manbaingressesResource, manbaingressesKind, c.ns, opts), &v1beta1.ManbaIngressList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.ManbaIngressList{ListMeta: obj.(*v1beta1.ManbaIngressList).ListMeta}
	for _, item := range obj.(*v1beta1.ManbaIngressList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested manbaIngresses.
func (c *FakeManbaIngresses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(manbaingressesResource, c.ns, opts))

}

// Create takes the representation of a manbaIngress and creates it.  Returns the server's representation of the manbaIngress, and an error, if there is any.
func (c *FakeManbaIngresses) Create(manbaIngress *v1beta1.ManbaIngress) (result *v1beta1.ManbaIngress, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(manbaingressesResource, c.ns, manbaIngress), &v1beta1.ManbaIngress{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ManbaIngress), err
}

// Update takes the representation of a manbaIngress and updates it. Returns the server's representation of the manbaIngress, and an error, if there is any.
func (c *FakeManbaIngresses) Update(manbaIngress *v1beta1.ManbaIngress) (result *v1beta1.ManbaIngress, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(manbaingressesResource, c.ns, manbaIngress), &v1beta1.ManbaIngress{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ManbaIngress), err
}

// Delete takes name of the manbaIngress and deletes it. Returns an error if one occurs.
func (c *FakeManbaIngresses) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(manbaingressesResource, c.ns, name), &v1beta1.ManbaIngress{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeManbaIngresses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(manbaingressesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.ManbaIngressList{})
	return err
}

// Patch applies the patch and returns the patched manbaIngress.
func (c *FakeManbaIngresses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.ManbaIngress, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(manbaingressesResource, c.ns, name, pt, data, subresources...), &v1beta1.ManbaIngress{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ManbaIngress), err
}
