apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: manbaingresses.configuration.manba.io
spec:
  group: configuration.manba.io
  version: v1beta1
  scope: Namespaced
  names:
    kind: ManbaIngress
    plural: manbaingresses
    shortNames:
    - mi
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            hosts:
              type: array
              items:
                type: string
            http:
              type: array
              items:
                type: object
                properties:
                  match:
                    type: array
                    items:
                      type: object
                      properties:
                        uri:
                          type: object
                          properties:
                            pattern:
                              type: string
                        method: &method
                          type: string
                          enum:
                          - GET
                          - POST
                          - PUT
                          - DELETE
                  rewrite:
                    type: object
                    properties:
                      uri:
                        type: string
                  ipAccessControl: &ipAccessControl
                    type: object
                    properties:
                      whitelist:
                        type: array
                        items:
                          type: string
                          pattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$
                      blacklist:
                        type: array
                        items:
                          type: string
                          pattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$ 
                  retry: &retry
                        type: object
                        properties:
                          interval:
                            type: integer
                          maxTimes:
                            type: integer
                          codes:
                            type: array
                            items:
                              type: integer
                  renderTemplate:
                      type: object
                      properties:
                        objects:
                          type: array
                          items:
                            type: object
                            properties: &renderObject
                              name:
                                type: string
                              flatAttrs:
                                type: boolean
                              attrs:
                                type: array
                                items:
                                  type: object
                                  properties: &renderAttr
                                    name:
                                      type: string
                                    extractExp:
                                      type: string
                  defaultValue: &defaultValue
                    type: object
                    properties:
                      body:
                        type: string
                      headers: &pairValues
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            value:
                              type: string
                      cookies: *pairValues
                      code:
                        type: integer
                  authFilter:
                    type: string
                  trafficPolicy: &trafficPolicy
                    type: object
                    properties:
                      loadBalancer:
                        type: string
                        enum:
                        - RoundRobin
                        - IPHash
                      maxQPS: &maxQPS
                        type: integer
                        minimum: 0
                      rateLimitOption:
                        type: string
                      circuitBreaker: &circuitBreaker
                        type: object
                        properties:
                          closeTimeout:
                            type: integer
                          halfTrafficRate:
                            type: integer
                          rateCheckPeriod:
                            type: integer
                          failureRateToClose:
                            type: integer
                          succeedRateToOpen:
                            type: integer
                  route:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        subset:
                          type: string
                        port:
                          type: integer

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: manbaclusters.configuration.manba.io
spec:
  group: configuration.manba.io
  version: v1beta1
  scope: Namespaced
  names:
    kind: ManbaCluster
    plural: manbaclusters
    shortNames:
    - ms
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            trafficPolicy: &trafficPolicy
              type: object
              properties:
                loadBalancer:
                  type: string
                  enum:
                  - RoundRobin
                  - IPHash
                maxQPS: &maxQPS
                  type: integer
                  minimum: 0
                rateLimitOption:
                  type: string
                circuitBreaker: &circuitBreaker
                  type: object
                  properties:
                    closeTimeout:
                      type: integer
                    halfTrafficRate:
                      type: integer
                    rateCheckPeriod:
                      type: integer
                    failureRateToClose:
                      type: integer
                    succeedRateToOpen:
                      type: integer
            subsets:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  labels:
                    type: object
                  trafficPolicy: *trafficPolicy 
            