apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: manbaingresses.configuration.manba.io
spec:
  group: configuration.manba.io
  version: v1beta1
  scope: Namespaced
  names:
    kind: ManbaIngress
    plural: manbaingresses
    shortNames:
    - mi
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            rules:
              type: array
              items:
                type: object
                properties:
                  host:
                    type: string
                  method: &method
                    type: string
                    enum:
                    - GET
                    - POST
                    - PUT
                    - DELETE
                  status: &status
                    type: string
                    enum:
                    - on
                    - off
                  ipAccessControl: &ipAccessControl
                    type: object
                    properties:
                      whitelist:
                        type: array
                        items:
                          type: string
                          pattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$
                      blacklist:
                        type: array
                        items:
                          type: string
                          pattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$
                  defaultValue: &defaultValue
                    type: object
                    properties:
                      body:
                        type: string
                      headers: &pairValues
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            value:
                              type: string
                      cookies: *pairValues
                      code:
                        type: integer
                  useDefault:
                    type: boolean
                  circuitBreaker: &circuitBreaker
                    type: object
                    properties:
                      closeTimeout:
                        type: integer
                      halfTrafficRate:
                        type: integer
                      rateCheckPeriod:
                        type: integer
                      failureRateToClose:
                        type: integer
                      succeedRateToOpen:
                        type: integer
                  authFilter:
                    type: string
                  maxQPS: &maxQPS
                    type: integer
                    minimum: 0
                  rateLimitOption:
                    type: string
                  backend: &backend
                    type: object
                    properties:
                      serviceName:
                        type: string
                      servicePort:
                        type: string
                      urlRewrite: &url
                        type: string
                        pattern: ^/.*$
                      attrName:
                        type: string
                      validations:
                        type: array
                        items: &validation
                          type: object
                          properties:
                            parameter: &parameter
                              type: object
                              properties:
                                name:
                                  type: string
                                source:
                                  type: string
                                  enum:
                                  - queryString
                                  - formData
                                  - jsonBody
                                  - header
                                  - cookie
                                  - pathValue
                                index:
                                  type: integer
                            required:
                              type: boolean
                            rules:
                              type: array
                              items: &validationRule
                                type: object
                                properties:
                                  ruleType:
                                    type: string
                                    enum:
                                    - ruleRegexp
                                  expression:
                                    type: string
                      cache:
                        type: object
                        properties:
                          keys:
                            type: array
                            items: *parameter
                          deadline:
                            type: integer
                          conditions: &conditions
                            type: array
                            items:
                              type: object
                              properties:
                                parameter: *parameter
                                cmp:
                                  type: string
                                  enum:
                                  - CMPEQ
                                  - CMPLT
                                  - CMPLE
                                  - CMPGT
                                  - CMPGE
                                  - CMPIn
                                  - CMPMatch
                                expect:
                                  type: string
                      defaultValue: *defaultValue
                      useDefault:
                        type: boolean
                      batchIndex:
                        type: integer
                      retryStrategy:
                        type: object
                        properties:
                          interval:
                            type: integer
                          maxTimes:
                            type: integer
                          codes:
                            type: array
                            items:
                              type: integer
                      writeTimeout:
                        type: integer
                      readTimeout:
                        type: integer
                      hostType:
                        type: string
                      customHost:
                        type: string
                  paths:
                    type: array
                    items:
                      type: object
                      properties:
                        method: *method
                        urlPattern: *url
                        status: *status
                        defaultValue: *defaultValue
                        perms:
                          type: array
                          items:
                            type: string
                        authFilter:
                          type: string
                        renderTemplate:
                          type: array
                          items:
                            type: object
                            properties:
                              objects:
                                type: array
                                items:
                                  type: object
                                  properties: &renderObject
                                    name:
                                      type: string
                                    flatAttrs:
                                      type: boolean
                                    attrs:
                                      type: array
                                      items:
                                        type: object
                                        properties: &renderAttr
                                          name:
                                            type: string
                                          extractExp:
                                            type: string
                        useDefault:
                          type: boolean
                        matchRule:
                          type: string
                        position:
                          type: integer
                        tags: *pairValues
                        webSocketOptions:
                          type: object
                          properties:
                            origin:
                              type: string
                        maxQPS: *maxQPS
                        circuitBreaker: *circuitBreaker
                        rateLimitOption:
                          type: string
                        backends:
                          type: array
                          items: *backend
                        route:
                          type: object
                          properties:
                            status: *status
                            strategy:
                              type: string
                            trafficRate:
                              type: integer
                            conditions: *conditions
