---
apiVersion: v1
kind: Service
metadata:
  name: manba-validation-webhook
  namespace: manba
spec:
  ports:
    - name: webhook
      port: 443
      protocol: TCP
      targetPort: 8081
  selector:
    app: manba-ingress
