/*
Copyright 2020 The Manba Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1beta1 "github.com/domgoer/manba-ingress/pkg/apis/configuration/v1beta1"
	scheme "github.com/domgoer/manba-ingress/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ManbaIngressesGetter has a method to return a ManbaIngressInterface.
// A group's client should implement this interface.
type ManbaIngressesGetter interface {
	ManbaIngresses(namespace string) ManbaIngressInterface
}

// ManbaIngressInterface has methods to work with ManbaIngress resources.
type ManbaIngressInterface interface {
	Create(*v1beta1.ManbaIngress) (*v1beta1.ManbaIngress, error)
	Update(*v1beta1.ManbaIngress) (*v1beta1.ManbaIngress, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.ManbaIngress, error)
	List(opts v1.ListOptions) (*v1beta1.ManbaIngressList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.ManbaIngress, err error)
	ManbaIngressExpansion
}

// manbaIngresses implements ManbaIngressInterface
type manbaIngresses struct {
	client rest.Interface
	ns     string
}

// newManbaIngresses returns a ManbaIngresses
func newManbaIngresses(c *ConfigurationV1beta1Client, namespace string) *manbaIngresses {
	return &manbaIngresses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the manbaIngress, and returns the corresponding manbaIngress object, and an error if there is any.
func (c *manbaIngresses) Get(name string, options v1.GetOptions) (result *v1beta1.ManbaIngress, err error) {
	result = &v1beta1.ManbaIngress{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("manbaingresses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ManbaIngresses that match those selectors.
func (c *manbaIngresses) List(opts v1.ListOptions) (result *v1beta1.ManbaIngressList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.ManbaIngressList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("manbaingresses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested manbaIngresses.
func (c *manbaIngresses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("manbaingresses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a manbaIngress and creates it.  Returns the server's representation of the manbaIngress, and an error, if there is any.
func (c *manbaIngresses) Create(manbaIngress *v1beta1.ManbaIngress) (result *v1beta1.ManbaIngress, err error) {
	result = &v1beta1.ManbaIngress{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("manbaingresses").
		Body(manbaIngress).
		Do().
		Into(result)
	return
}

// Update takes the representation of a manbaIngress and updates it. Returns the server's representation of the manbaIngress, and an error, if there is any.
func (c *manbaIngresses) Update(manbaIngress *v1beta1.ManbaIngress) (result *v1beta1.ManbaIngress, err error) {
	result = &v1beta1.ManbaIngress{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("manbaingresses").
		Name(manbaIngress.Name).
		Body(manbaIngress).
		Do().
		Into(result)
	return
}

// Delete takes name of the manbaIngress and deletes it. Returns an error if one occurs.
func (c *manbaIngresses) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("manbaingresses").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *manbaIngresses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("manbaingresses").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched manbaIngress.
func (c *manbaIngresses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.ManbaIngress, err error) {
	result = &v1beta1.ManbaIngress{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("manbaingresses").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
